service: contact-101photographers

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev

functions:
  hello:
    handler: handler.sendContactEmail
    events:
      - http:
          path: contact-us
          method: POST

resources:
  Resources:
    contactUsEmail:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-contactus
