service: contact

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.sendContactEmail

resources:
  Resources:
    S3BucketMybucket101photographersEmail:
      Type: S3::Bucket
