service: contact-101photographers

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "ses:SendEmail"
       Resource:
         - "arn:aws:ses:us-east-1:617796983124:identity/101photographers.in"
         - "arn:aws:ses:us-east-1:617796983124:identity/satiesharma@gmail.com"
         - "arn:aws:ses:us-east-1:617796983124:identity/devasar@gmail.com"

functions:
  hello:
    handler: handler.sendContactEmail
    events:
      - http:
          path: contact-us
          method: POST
          cors: true          

resources:
  Resources:
    contactUsEmail:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-contactus
